#cloud-config
package_update: true
packages:
  - awscli

runcmd:
  - mkdir -p /root/.aws
  - echo "[default]" > /root/.aws/credentials
  - echo "aws_access_key_id = YCAJEs1XI6G03h_n8DoTN4rKT" >> /root/.aws/credentials
  - echo "aws_secret_access_key = YCOOaeK8_7GiShRyalXFjVqvAPqBX78DUsGMyLiG" >> /root/.aws/credentials
  - echo "[default]" > /root/.aws/config
  - echo "region = ru-central1-b" >> /root/.aws/config
  - echo "output = json" >> /root/.aws/config
  - echo "endpoint_url = https://storage.yandexcloud.net" >> /root/.aws/config
  - echo "Test" > /root/test.txt
  - aws --endpoint-url=https://storage.yandexcloud.net s3 cp /root/test.txt s3://ilartstu-mlflow/
