name: CD

# on:
#   push:
#     branches: [ main ]
#     # или можно запускать по релизу, если хотите: 
#     # tags: [ 'v*.*.*' ]

jobs:
  deploy-infra:
    name: Deploy Terraform (Yandex.Cloud)
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > hashicorp.gpg
        sudo install -o root -g root -m 644 hashicorp.gpg /usr/share/keyrings/
        sudo apt-get update && sudo apt-get install -y terraform

    - name: Terraform Init & Apply
      working-directory: Terraform
      env:
        YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SA_KEY }}  # JSON YC
      run: |
        terraform init
        terraform apply -auto-approve

  push-docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: deploy-infra

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push bot image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/texture-bot:latest .
        docker push ${{ secrets.DOCKERHUB_USER }}/texture-bot:latest
