name: CI Minimal Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-build-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install and check Python dependencies
      working-directory: MLFlow_texture_bot
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt mlflow
        pip install flake8
        flake8 .

    - name: Build Docker image for bot
      working-directory: MLFlow_texture_bot
      run: docker build -t texture-bot-local .

    - name: Init & validate Terraform, then plan
      working-directory: Terraform
      run: |
        # Устанавливаем Terraform
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > hashicorp.gpg
        sudo install -o root -g root -m 644 hashicorp.gpg /usr/share/keyrings/
        sudo apt-get update && sudo apt-get install -y terraform
        # Terraform steps
        terraform init -input=false
        terraform validate
        terraform plan -out=tfplan
