name: CI Minimal Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-build-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      working-directory: MLFlow_texture_bot
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt mlflow

    - name: Build Docker image for bot
      working-directory: MLFlow_texture_bot
      run: docker build -t texture-bot-local .

    - name: Init & validate Terraform, then plan
      working-directory: Terraform
      run: |
        # 1) Устанавливаем необходимые утилиты
        sudo apt-get update
        sudo apt-get install -y \
          gnupg software-properties-common curl lsb-release

        # 2) Добавляем GPG-ключ и репозиторий HashiCorp
        curl -fsSL https://apt.releases.hashicorp.com/gpg | \
          sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com \
          $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list

        # 3) Устанавливаем Terraform
        sudo apt-get update
        sudo apt-get install -y terraform

        # 4) Проверяем Terraform
        terraform version

        # 5) Инициализируем, валидируем и планим
        terraform init -input=false
        terraform validate
        terraform plan -out=tfplan
